#-------------------------------
# Site Settings
title: MELISSA CASTELLE
description: Heart of Art, Mind of Logic.
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
      #Ici PCG, Houdini, FluidFlux,Speedtree,Nanite Assemblies
    - title: 'Procedural/Systems'
      url: '/procedural-systems/'
      #Ici Lamp BP tool, name validation script, asset validation script, Guidelines pour Artistes type naming conventions
    - title: 'Tools/Pipeline'
      url: '/tools-pipeline/'
      #Ici ShaderGraph Materials (Layered materials,Vertex animation,RimLighting), Optimization focused shaders, VFX, Raymarching/procedural surfaces (fog,clouds), Lighting/Rendering techniques
    - title: 'Rendering and Shaders'
      url: '/rendering-shaders/'
      submenu:
      - url: '/about/'
        title: 'About'
      - url: '/contact/'
        title: 'Contact'
      - url: '/techartducks/'
        title: 'TechArtDucks'
      - title: 'Events'
      url: '/events/'


#-------------------------------
# Author Settings
author:
  author_name: M√©lissa Castelle
  author_avatar: /images/01-1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/01-1.jpg
  hero_title: "Hi! I'm Melissaüåª"
  hero_subtitle: A technical artist, former environment artist, and nerdy mom.
  hero_description: |
    Hey, I‚Äôm M√©lissa ‚Äî Technical Artist focused on real-time environments, procedural systems, and production-ready solutions.

    Here, I document my work, share the tools and techniques I use, and break down the systems and workflows behind my projects. From procedural environments and Blueprint setups to optimization strategies and shader experiments, this is where I show how I solve problems and bring ideas to life.  

    Explore, learn, and get a behind-the-scenes look at my Technical Art journey ‚Äî and feel free to share your thoughts or questions along the way!

  hero_image_caption: My creative space, where new worlds are born
  hero_button_text: Let‚Äôs Work Together
  hero_button_link: '/contact/'
  herp_image: /images/01-1.jpg

#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: true
  gallery_section_title: My Work
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/100.jpg'
        caption: 'Small steps lead to big results.'
      - alt: 'Lifestyle'
        url: '/images/101.jpg'
        caption: 'A peaceful moment captured during a serene evening.'
      - alt: 'Hobby'
        url: '/images/102.jpg'
        caption: 'True friends are like stars ‚Äî they shine brightest when the world feels dark.'
      - alt: 'Computers'
        url: '/images/103.jpg'
        caption: 'Every click opens a new chapter in an endless story.'
      - alt: 'Games'
        url: '/images/104.jpg'
        caption: 'Every level is a new opportunity to test your limits.'

#-------------------------------
# Logos
logos:
  enable: true
  logos_title: Projects I worked on
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"
#-------------------------------
# Videos Section Settings
videos_section:
  enable: true
  videos_section_title: Latest Videos

#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: My Last Posts


#-------------------------------
# Newsletter Settings
#mailchimp:
  #enable: true
  #mailchimp_title: Stay inspired weekly ‚úåÔ∏è
  #mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  #mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  #mailchimp_input_text: Your email address...
  #mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
footer_description: Here, I share ideas, tools, and methods that help me balance productivity with creativity while keeping control over my digital world. Dive in, get inspired, and feel free to share your thoughts!


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "X", link: "https://x.com/MelissaCastelle"}
- {icon: "fa-brands fa-artstation", name: "Artstation", link: "https://www.artstation.com/techartducks"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/m%C3%A9lissa-castelle-873885105/"}
- {icon: "fa-brands fa-youtube", name: "YouTube", link: "https://www.youtube.com/@TechArtDucks"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/MelissaCastelle"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: melissa.castelle.ta@gmail.com # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
